### ISSUE TITLE
Missing syntax check for definition of state variables

### ISSUE THREAD

**Issue by HoppelHSIE** [lf-lang/lingua-franca#1149]
During figuring out how to define an array as a state variable of a reactor in Lingua Franca I discovered that defining it syntactically wrong like "state <variable>()" does not lead to an error or problem message although the program does not compile and run due to this error. Therefore, I suggest including a corresponding syntactical check in future releases.

**Comment by erlingrj** [comment]
Just having "state ()" leads to an error message both in Epoch and VSCode here

**Comment by SiegfriedHollerer** [comment]
Sorry, it seems that during copy & paste from slack some information disappeared...

The described behaviour occured when defining a variable, so "state <variable>()" was used instead of "state ()".

**Comment by erlingrj** [comment]
Aha, I can also now reproduce this error. Nice catch. 

```
target Python

main reactor {
  state a()
  
  reaction(startup) {=
    print("Hello world")
   =}
``` 

Give following error
```
lfc: fatal error: An unexpected error occurred:
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.lflang.generator.python.PythonStateGenerator.generatePythonInitializer(PythonStateGenerator.java:39)
        at org.lflang.generator.python.PythonStateGenerator.generatePythonInstantiations(PythonStateGenerator.java:24)
        at org.lflang.generator.python.PythonReactorGenerator.generatePythonConstructor(PythonReactorGenerator.java:93)
        at org.lflang.generator.python.PythonReactorGenerator.generatePythonClass(PythonReactorGenerator.java:56)
        at org.lflang.generator.python.PythonReactorGenerator.generatePythonClass(PythonReactorGenerator.java:26)
        at org.lflang.generator.python.PythonGenerator.generatePythonReactorClasses(PythonGenerator.java:176)
        at org.lflang.generator.python.PythonGenerator.generatePythonCode(PythonGenerator.java:225)
        at org.lflang.generator.python.PythonGenerator.generatePythonFiles(PythonGenerator.java:291)
        at org.lflang.generator.python.PythonGenerator.doGenerate(PythonGenerator.java:649)
        at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:164)
        at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
        at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
        at org.lflang.lfc.Main.runGenerator(Main.java:293)
        at org.lflang.lfc.Main.main(Main.java:222)
```
