### ISSUE TITLE
java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1363]
[This PR run](https://github.com/lf-lang/reactor-c/actions/runs/3048968494) is unrelated to our Java sources or build system. It adds a Markdown file in `reactor-c`. It fails with a `java.lang.SecurityException`:

```
java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
                                    at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1158)
                                    at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:902)
                                    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
                                    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
                                    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
                                    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
                                    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
                                    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
                                    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
                                    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
                                    at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
                                    at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
                                    at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2555)
                                    at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:292)
                                    at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:117)
                                    at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:716)
                                    at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:941)
                                    at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
                                    at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:301)
                                    at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:224)
                                    at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:39)
                                    at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:131)
                                    at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:97)
                                    at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:40)
                                    at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:49)
                                    at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
                                    at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
                                    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
                                    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
                                    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
                                    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
```

Other CI runs, such as [this one](https://github.com/lf-lang/lingua-franca/actions/runs/3047606233/jobs/4912161892), are failing with the same errors. It is 5 PM, Tuesday, September 13, and I believe that this issue appeared in the past hour. I am able to reproduce this issue locally in `master` after deleting my local `.gradle` caches. I suspect that this issue is unrelated to recent changes in our code base.

**Comment by lhstrh** [comment]
Oh, this is the same error that @CloverCho was encountering just now!

**Comment by lhstrh** [comment]
Attempted fix: https://github.com/lf-lang/lingua-franca/pull/1364
