### ISSUE TITLE
Error message displayed on missing submodules points to outdated links

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1428]
If a submodule is missing, lfc currently prints this message:
```
xception in thread "main" java.io.IOException: A required target resource could not be found: /lib/cpp/reactor-cpp
Perhaps a git submodule is missing or not up to date.
See https://github.com/icyphy/lingua-franca/wiki/downloading-and-building#clone-the-lingua-franca-repository.
Also try to refresh and clean the project explorer if working from eclipse.
    at org.lflang.util.FileUtil.copyDirectoryFromClassPath(FileUtil.java:320)
    at org.lflang.generator.cpp.CppGenerator.generateFiles(CppGenerator.kt:142)
    at org.lflang.generator.cpp.CppGenerator.doGenerate(CppGenerator.kt:77)
    at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:164)
    at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
    at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
    at org.lflang.cli.Lfc.runGenerator(Lfc.java:245)
    at org.lflang.cli.Lfc.main(Lfc.java:182)
```
This points to an outdated wiki page that does not seem to mention submodules. I thought this should be an easy fix, but I could't find any resources on our website explaining how to deal with submodules either. Moreover, the instructions on how to clone the repository do not seem to provide the instructions needed to also fetch all submodules.

**Comment by edwardalee** [comment]
A good place to put these instructions would be here:

[https://www.lf-lang.org/docs/handbook/download?target=c#the-repository](https://www.lf-lang.org/docs/handbook/download?target=c#the-repository)

**Comment by lhstrh** [comment]
According to `rg`, this text is no longer present in the code base. Closing.
