### ISSUE TITLE
Language Server not generating diagrams

### ISSUE THREAD

**Issue by arengarajan99** [lf-lang/lingua-franca#1634]
Platform: Apple M1 Pro 2021, OS Version 13.2.1
Java Version:
```
java --version
openjdk 17.0.4 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)
```

VS Code is not able to generate diagrams. Here is the stacktrace: 

```
[Info  - 3:36:06 PM] Generating diagram for input: 'file:///Users/arengarajan/Documents/GitHub/LinguaFranca/lingua-franca/test/C/src/federated/LoopDistributedCentralized.lf'
Mar 09, 2023 3:36:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint notify
WARNING: Failed to send notification message.
java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile java.lang.String java.lang.Thread.name accessible: module java.base does not "opens java.lang" to unnamed module @d310a75
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:138)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:40)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at org.eclipse.sprotty.server.json.PropertyBasedTypeAdapter.writeProperty(PropertyBasedTypeAdapter.java:212)
	at org.eclipse.sprotty.server.json.PropertyBasedTypeAdapter.writeProperties(PropertyBasedTypeAdapter.java:194)
	at org.eclipse.sprotty.server.json.PropertyBasedTypeAdapter.write(PropertyBasedTypeAdapter.java:178)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:434)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:145)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:59)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:68)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:112)
	at jdk.proxy2/jdk.proxy2.$Proxy39.notify(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at jdk.proxy2/jdk.proxy2.$Proxy42.accept(Unknown Source)
	at org.eclipse.sprotty.xtext.ls.DiagramServerManager.lambda$getDiagramServer$1(DiagramServerManager.java:166)
	at org.eclipse.sprotty.DefaultDiagramServer.dispatch(DefaultDiagramServer.java:195)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.updateDiagramOptions(KGraphDiagramServer.java:257)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramServer.prepareUpdateModel(KGraphDiagramServer.java:222)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater$2.accept(KGraphDiagramUpdater.java:144)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater$2.accept(KGraphDiagramUpdater.java:1)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.complete(AbstractRequest.java:65)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[Error - 3:38:23 PM] Error during request: : java.util.concurrent.CompletionException: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4944r26 in java.library.path: /Users/arengarajan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt-cocoa in java.library.path: /Users/arengarajan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt in java.library.path: /Users/arengarajan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt-cocoa-4944r26.jnilib
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt.jnilib
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt-cocoa-4944r26.jnilib

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1527)
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1517)
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1517)
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1519)
	at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2419)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.cancel(RequestManager.java:114)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.runWrite(RequestManager.java:80)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.runBuildable(LanguageServerImpl.java:458)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.didChangeWatchedFiles(LanguageServerImpl.java:429)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:68)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4944r26 in java.library.path: /Users/arengarajan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt-cocoa in java.library.path: /Users/arengarajan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt in java.library.path: /Users/arengarajan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt-cocoa-4944r26.jnilib
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt.jnilib
	Can't load library: /Users/arengarajan/.swt/lib/macosx/aarch64/libswt-cocoa-4944r26.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:348)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:107)
	at de.cau.cs.kieler.klighd.microlayout.PlacementUtil.estimateTextSize(PlacementUtil.java:1018)
	at de.cau.cs.kieler.klighd.microlayout.PlacementUtil.estimateTextSize(PlacementUtil.java:940)
	at de.cau.cs.kieler.klighd.microlayout.PlacementUtil.estimateSize(PlacementUtil.java:546)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis$7.apply(EObjectFallbackSynthesis.java:439)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis$7.apply(EObjectFallbackSynthesis.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:140)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis.transformToPort(EObjectFallbackSynthesis.java:444)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis.access$4(EObjectFallbackSynthesis.java:425)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis$3.apply(EObjectFallbackSynthesis.java:193)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis$3.apply(EObjectFallbackSynthesis.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:140)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis.transform(EObjectFallbackSynthesis.java:207)
	at de.cau.cs.kieler.klighd.ide.syntheses.EObjectFallbackSynthesis.transform(EObjectFallbackSynthesis.java:1)
	at de.cau.cs.kieler.klighd.syntheses.AbstractDiagramSynthesis.transform(AbstractDiagramSynthesis.java:220)
	at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.transform(ReinitializingDiagramSynthesisProxy.java:290)
	at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:454)
	at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:389)
	at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:346)
	at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater$5.accept(KGraphDiagramUpdater.java:263)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer$2.accept(AbstractLanguageServer.java:124)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer$2.accept(AbstractLanguageServer.java:1)
	at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.configureAndRun(AbstractLanguageServer.java:101)
	at org.lflang.diagram.lsp.LanguageDiagramServer.start(LanguageDiagramServer.java:90)
	at org.lflang.diagram.lsp.LanguageDiagramServer.main(LanguageDiagramServer.java:86)
```

**Comment by lhstrh** [comment]
This should be fixed. Please re-open if there are still issues, @arengarajan99.
