### ISSUE TITLE
`IndexOutOfBoundsException` in language server

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1683]
```
Mar 31, 2023 2:39:35 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "generator/partialBuild",
  "params": "file:///home/peter/examples-lingua-franca/C/src/DistributedDatabase/ReplicatedDatabaseNoCycles.lf"
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:68)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.IllegalArgumentException: -1
	at java.base/java.util.stream.ReferencePipeline.skip(ReferencePipeline.java:575)
	at org.lflang.generator.LanguageServerErrorReporter.getLine(LanguageServerErrorReporter.java:186)
	at org.lflang.generator.LanguageServerErrorReporter.report(LanguageServerErrorReporter.java:115)
	at org.lflang.generator.LanguageServerErrorReporter.reportError(LanguageServerErrorReporter.java:88)
	at org.lflang.generator.IntegratedBuilder.validate(IntegratedBuilder.java:105)
	at org.lflang.generator.IntegratedBuilder.run(IntegratedBuilder.java:88)
	at org.lflang.diagram.lsp.LFLanguageServerExtension.buildWithProgress(LFLanguageServerExtension.java:117)
	at org.lflang.diagram.lsp.LFLanguageServerExtension.partialBuild(LFLanguageServerExtension.java:76)
	... 16 more
```

Will update with steps to reproduce if time permits

**Comment by petervdonovan** [comment]
This occurs when a nonexistent parameter is used to specify the width of a multiport. It appears that an error is reported on a line that is out of bounds.
