### ISSUE TITLE
File system exception on Windows

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1799]
```
lfc: fatal error: Error running generator
org.eclipse.xtext.util.RuntimeIOException: java.nio.file.FileAlreadyExistsException: C:\lingua-franca\test\C\src-gen\HelloWorld\include\core
        at org.lflang.util.FileUtil.lambda$copyDirectoryContents$0(FileUtil.java:199)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.lflang.util.FileUtil.copyDirectoryContents(FileUtil.java:186)
        at org.lflang.generator.c.CGenerator.generateHeaders(CGenerator.java:902)
        at org.lflang.generator.c.CGenerator.doGenerate(CGenerator.java:420)
        at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:186)
        at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
        at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
        at org.lflang.cli.Lfc.invokeGenerator(Lfc.java:187)
        at org.lflang.cli.Lfc.doRun(Lfc.java:150)
        at org.lflang.cli.CliBase.run(CliBase.java:138)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.lflang.cli.CliBase.doExecute(CliBase.java:110)
        at org.lflang.cli.CliBase.cliMain(CliBase.java:102)
        at org.lflang.cli.Lfc.main(Lfc.java:137)
        at org.lflang.cli.Lfc.main(Lfc.java:127)
Caused by: java.nio.file.FileAlreadyExistsException: C:\lingua-franca\test\C\src-gen\HelloWorld\include\core
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
        at java.base/java.nio.file.Files.createDirectory(Files.java:700)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:753)
        at org.lflang.util.FileUtil.lambda$copyDirectoryContents$0(FileUtil.java:196)
        ... 31 more
```

Solution: make our implementation of `copyDirectoryContents` not fail on Windows when the directory already exists.

**Comment by petervdonovan** [comment]
Closing this because it is stale and is already labeled as a`wontfix`.
