### ISSUE TITLE
Nondeterministic segmentation fault

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1838]
Actually, this is a nondeterministic segmentation fault (sometimes it happens, usually it doesn't), so probably it affects other Python federated tests as well. It happens during garbage collection; here is the stack trace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  gc_reset_refs (
    refs=<error reading variable: Cannot access memory at address 0x10>, g=0x0)
    at ../Modules/gcmodule.c:105
105     ../Modules/gcmodule.c: No such file or directory.
[Current thread is 1 (Thread 0x7f78704c4000 (LWP 45104))]
(gdb) bt
#0  gc_reset_refs (
    refs=<error reading variable: Cannot access memory at address 0x10>, g=0x0)
    at ../Modules/gcmodule.c:105
#1  update_refs (containers=containers@entry=0x565479446e30)
    at ../Modules/gcmodule.c:427
#2  deduce_unreachable (base=base@entry=0x565479446e30, 
    unreachable=unreachable@entry=0x7ffe0006e530) at ../Modules/gcmodule.c:1104
#3  0x00005654786b9625 in gc_collect_main (tstate=0x565479462f40, generation=2, 
    n_collected=0x7ffe0006e5f8, n_uncollectable=0x7ffe0006e5f0, nofail=0)
    at ../Modules/gcmodule.c:1239
#4  0x00005654787c0f50 in gc_collect_with_callback (tstate=0x565479462f40, 
    generation=2) at ../Modules/gcmodule.c:1413
#5  0x00005654787f44be in PyGC_Collect () at ../Modules/gcmodule.c:2099
#6  0x00005654787f1efe in Py_FinalizeEx () at ../Python/pylifecycle.c:1781
#7  0x00005654787e1af3 in Py_RunMain () at ../Modules/main.c:668
#8  0x00005654787b7bcd in Py_BytesMain (argc=<optimized out>, argv=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../Modules/main.c:720
#9  0x00007f7870229d90 in __libc_start_call_main (
    main=main@entry=0x5654787b7b90 <main>, argc=argc@entry=4, argv=argv@entry=0x7ffe0006e8d8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007f7870229e40 in __libc_start_main_impl (main=0x5654787b7b90 <main>, argc=4, 
    argv=0x7ffe0006e8d8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe0006e8c8) at ../csu/libc-start.c:392
#11 0x00005654787b7ac5 in _start ()
```

Could this be related to the problem that @jackykwok2024 is working on?

_Originally posted by @petervdonovan in https://github.com/lf-lang/lingua-franca/issues/1835#issuecomment-1585036043_

**Comment by lhstrh** [comment]
I haven't seen these kinds of problems lately. Has this been fixed?

**Comment by Jakio815** [comment]
Looks like it still happens. But I'm not sure if it's my problem or the CI test's problem. I find it here #2070 .
