### ISSUE TITLE
Unrecognized platform causes NPE

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1919]
I tried to compile a pico example without having the branch implementing the platform support installed, and got the following error:
```
  lfc: fatal error: Error running generator
   java.lang.NullPointerException: Cannot invoke "org.lflang.TargetProperty$Platform.toString()" because "this.targetConfig.platformOptions.platform" is null
           at org.lflang.generator.c.CGenerator.pickCompilePlatform(CGenerator.java:902)
           at org.lflang.generator.c.CGenerator.setUpGeneralParameters(CGenerator.java:2007)
           at org.lflang.generator.c.CGenerator.doGenerate(CGenerator.java:397)
           at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:115)
           at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
           at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
           at org.lflang.cli.Lfc.invokeGenerator(Lfc.java:187)
           at org.lflang.cli.Lfc.doRun(Lfc.java:150)
           at org.lflang.cli.CliBase.run(CliBase.java:145)
           at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
           at picocli.CommandLine.access$1500(CommandLine.java:148)
           at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
           at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
           at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
           at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
           at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
           at picocli.CommandLine.execute(CommandLine.java:2170)
           at org.lflang.cli.CliBase.doExecute(CliBase.java:117)
           at org.lflang.cli.CliBase.cliMain(CliBase.java:109)
           at org.lflang.cli.Lfc.main(Lfc.java:137)
           at org.lflang.cli.Lfc.main(Lfc.java:127)
```

There should be a validator check that produces a graceful error if the specified platform is not supported.

**Comment by arengarajan99** [comment]
@cmnrd What was the contents of the lf file you were trying to run?

**Comment by cmnrd** [comment]
It was this example in the pico repo: https://github.com/lf-lang/lf-pico/blob/main/src/Blink.lf

**Comment by arengarajan99** [comment]
Added a fix in federated-target branch. It's designed to throw an AssertionError but I can have it default to Auto if it makes more logical sense.
