### ISSUE TITLE
Issue in diagrams synthesis

### ISSUE THREAD

**Issue by ChadliaJerad** [lf-lang/lingua-franca#1941]
In `VS Code`, when generating the diagram of this program:
````
target C {
  timeout: 10 s
}

reactor Count {
  state count: int = 0
  timer t(0, 1 s)

  reaction(t) {= lf_print("Count is: %d", self->count); =}
}
````
if the open folder is in the `lingua-franca` path (ex: `~/vscode-lingua-franca/lingua-franca`, or `~/vscode-lingua-franca/lingua-franca/test/C`), the generation succeeds.
If, however, the open folder is outside of the `lingua-franca` path, the following exception is thrown:
````
An exception occurred during diagram synthesis\ java.lang.IllegalArgumentException: Unable to determine target based on 
given EObject.\ &nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.FormattingUtil.inferTarget(FormattingUtil.java:88)\ 
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.FormattingUtil.render(FormattingUtil.java:46)\ &nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.ast.FormattingUtil.render(FormattingUtil.java:93)\ &nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.createStateVariableLabel(LinguaFrancaSynthesis.java:1515)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.addStateVariableList(LinguaFrancaSynthesis.java:1502)\ 
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.createReactorNode(LinguaFrancaSynthesis.java:609)\ 
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:333)\ 
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.synthesis.LinguaFrancaSynt...
````
The source is `KLighD Diagrams (Extension)`: v0.4.2

This pattern applies to most programs. For example, the diagram is generated for `~/vscode-lingua-franca/lingua-franca/test/C/src/ActionDelay.lf`. But when it is copied into `~/tests/src/ActionDelay.lf` (and open from `~/tests`), an illegal exception occurs:
````
An exception occurred during diagram synthesis\
java.lang.IllegalArgumentException: Unable to determine target based on given EObject.\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.FormattingUtil.inferTarget(FormattingUtil.java:88)\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.FormattingUtil.render(FormattingUtil.java:46)\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.FormattingUtil.render(FormattingUtil.java:93)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.createStateVariableLabel(LinguaFrancaSynthesis.java:1515)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.addStateVariableList(LinguaFrancaSynthesis.java:1502)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.createReactorNode(LinguaFrancaSynthesis.java:609)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transformReactorNetwork(LinguaFrancaSynthesis.java:1018)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.createReactorNode(LinguaFrancaSynthesis.java:480)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:318)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:141)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
de.cau.cs.kieler.klighd.syntheses.AbstractDiagramSynthesis.transform(AbstractDiagramSynthesis.java:220)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.transform(ReinitializingDiagramSynthesisProxy.java:289)\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:454)\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:389)\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:346)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater.lambda$6(KGraphDiagramUpdater.java:267)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.lambda$1(AbstractLanguageServer.java:117)\
&nbsp;&nbsp;&nbsp;&nbsp;at 
de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.configureAndRun(AbstractLanguageServer.java:96)\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.lsp.LanguageDiagramServer.start(LanguageDiagramServer.java:111)\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.lsp.LanguageDiagramServer.main(LanguageDiagramServer.java:107)\
````

**Comment by ChadliaJerad** [comment]
@soerendomroes: sharing the issue description. For I don't know what reason, I couldn't assign it to you.

**Comment by ChadliaJerad** [comment]
BTW, on `lingua-franca`, `matser` branch, calling `./gradlew build` leads to a failure in the diagram generation test for `Import.lf` (`DiagramGenerationTest > diagramGenerationTestFactory(Path) > test/TypeScript/src/Import.lf`):
````
DiagramGenerationTest > diagramGenerationTestFactory(Path) > test/TypeScript/src/Import.lf STANDARD_ERROR
    Unable to import file:/home/chadlia/berkeleyWorkspace/vscode-lingua-franca/lingua-franca/test/TypeScript/src/lib/Imported.lf: java.io.FileNotFoundException: /home/chadlia/berkeleyWorkspace/vscode-lingua-franca/lingua-franca/test/TypeScript/src/lib/Imported.lf (No such file or directory)

DiagramGenerationTest > diagramGenerationTestFactory(Path) > test/TypeScript/src/Import.lf STANDARD_OUT
    An exception occurred during diagram synthesis

DiagramGenerationTest > diagramGenerationTestFactory(Path) > test/TypeScript/src/Import.lf STANDARD_ERROR
    java.lang.NullPointerException: Cannot invoke "org.lflang.lf.Reactor.getTypeParms()" because "definition" is null
        at org.lflang.generator.c.TypeParameterizedReactor.<init>(TypeParameterizedReactor.java:84)
        at org.lflang.generator.c.TypeParameterizedReactor.<init>(TypeParameterizedReactor.java:35)
        at org.lflang.generator.ReactorInstance.<init>(ReactorInstance.java:820)
        at org.lflang.generator.ReactorInstance.<init>(ReactorInstance.java:882)
        at org.lflang.generator.ReactorInstance.<init>(ReactorInstance.java:105)
        at org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:315)
        at org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:141)
        at de.cau.cs.kieler.klighd.syntheses.AbstractDiagramSynthesis.transform(AbstractDiagramSynthesis.java:220)
        at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.transform(ReinitializingDiagramSynthesisProxy.java:289)
        at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:454)
        at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:389)
        at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:346)
        at de.cau.cs.kieler.klighd.LightDiagramServices.translateModel2(LightDiagramServices.java:474)
        at de.cau.cs.kieler.klighd.LightDiagramServices.renderOffScreen(LightDiagramServices.java:613)
        at de.cau.cs.kieler.klighd.LightDiagramServices.renderOffScreen(LightDiagramServices.java:534)
        at de.cau.cs.kieler.klighd.LightDiagramServices.renderOffScreen(LightDiagramServices.java:500)
        at org.lflang.cli.DiagramGenerationTest.run(DiagramGenerationTest.java:82)
        at org.lflang.cli.DiagramGenerationTest.lambda$diagramGenerationTestFactory$0(DiagramGenerationTest.java:61)
        at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$0(DynamicTestTestDescriptor.java:53)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptDynamicTest(InvocationInterceptor.java:167)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptDynamicTest(InvocationInterceptor.java:184)
        at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$1(DynamicTestTestDescriptor.java:61)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptorCall.lambda$ofVoid$0(InvocationInterceptorChain.java:78)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute(DynamicTestTestDescriptor.java:60)
        at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute(DynamicTestTestDescriptor.java:32)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:108)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:95)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

DiagramGenerationTest > diagramGenerationTestFactory(Path) > test/TypeScript/src/Import.lf FAILED
    java.lang.AssertionError
        at org.lflang.cli.DiagramGenerationTest.run(DiagramGenerationTest.java:87)
        at org.lflang.cli.DiagramGenerationTest.lambda$diagramGenerationTestFactory$0(DiagramGenerationTest.java:61)
````

**Comment by soerendomroes** [comment]
I did the following thing to replicate your problem:

1. Installed the 0.4.2 VS Code LF extension
2. Copied your program into a new file in my workspace.

The result is the following syntax error.
![image](https://github.com/lf-lang/lingua-franca/assets/6419799/1103d21d-585b-449d-829e-adf97bf1a223)
`no viable alternative at input '='`

If I remove the error, the diagram works fine.

What am I doing wrong? Is the released version not the correct one? Are you building and starting the LF extension locally?

**Comment by soerendomroes** [comment]
I also tried to replicate the issue by building the extension on the main branch but it also seems to work fine. Can you elaborate on your setup?

**Comment by petervdonovan** [comment]
This looks like two separate issues, the first of which definitely looks the same as #1930 as Alexander said.

**Comment by petervdonovan** [comment]
@ChadliaJerad I took a closer look at these two bug reports.

---

Regarding the **java.lang.IllegalArgumentException**: The code in its current state could not possibly produce the stack trace that you showed because `createStateVariableLabel` no longer calls `FormattingUtil.render`; instead, it directly invokes `ToLf.instance.doSwitch`. Therefore, your VS code extension is certainly not using the latest version of `lingua-franca`.

By the way, I think that **the 0.4.2 release of the lingua-franca VS Code is WAY out of date**, as illustrated by the syntax error that Soren mentioned. I would recommend that everyone switch to the pre-release version of the extension before reporting any new bugs:

![image](https://github.com/lf-lang/lingua-franca/assets/33707478/56586a6d-a2a9-4236-b9e8-046529ec1dd6)


---

Regarding the failure in `DiagramGenerationTest > diagramGenerationTestFactory(Path) > test/TypeScript/src/Import.lf`:

I could not reproduce the error that you reported on `master` when invoking `./gradlew build`. For me, on commit `6b4bb4c1d8eb76520bec96f7b51cee83b4213649`, `./gradlew build` finishes without errors, stating:
```
BUILD SUCCESSFUL in 55s
86 actionable tasks: 26 executed, 60 up-to-date
```

Indeed, I do not know how this error possibly could exist in `master` because it would have been caught by CI, which passed in the latest update of `master`. So your `master` must be out of date (i.e., older than `6b4bb4c`).

**Comment by ChadliaJerad** [comment]
Thanks for having a look, @soerendomroes, @a-sr, and @petervdonovan!

> I did the following thing to replicate your problem:
>
> Installed the 0.4.2 VS Code LF extension
> Copied your program into a new file in my workspace.
> The result is the following syntax error.
> image
> no viable alternative at input '='
>
> If I remove the error, the diagram works fine.
>
> What am I doing wrong? Is the released version not the correct one? Are you building and starting the LF extension locally?

Currently: I am on `master` (up-to-date) in `lingua-franca`.
My editor does not complain about the equal sign (in the textual version like yours). The exception is thrown in both cases unless the file is opened from somewhere in the `lingua-franca` path.

> I also tried to replicate the issue by building the extension on the main branch but it also seems to work fine. Can you elaborate on your setup?


I also use [vscode-lingua-franca](https://github.com/lf-lang/vscode-lingua-franca), so I am assuming I am using a built extension (also because at some point, the editor was not complaining about the features I added in my working branch).
Still, I just tried to run again `npm install`, and got this error:
 
````
> vscode-lingua-franca@0.4.2 install
> npm run clean && npm run build && npm run package && npm run deploy


> vscode-lingua-franca@0.4.2 clean
> rimraf out && rimraf lib && rimraf vscode-lingua-franca-*.vsix

npm notice 
npm notice New minor version of npm available! 9.6.6 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 

> vscode-lingua-franca@0.4.2 build
> npx ts-node src/build_lds.ts

> checking dependencies...
> code [found]
> jar [found]
> javac [found]
> mvn [found]
> python3 [found]
> verifying Java compiler version...
> Java compiler version is 17.0.5
> updating Git submodules...
> starting Gradle build...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
22 actionable tasks: 2 executed, 20 up-to-date
npm notice 
npm notice New minor version of npm available! 9.6.6 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 
npm notice 
npm notice New minor version of npm available! 9.6.6 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 

> vscode-lingua-franca@0.4.2 package
> move-cli lingua-franca ../temp-lingua-franca89539275 && vsce package && move-cli ../temp-lingua-franca89539275 lingua-franca

[Error: ENOTEMPTY: directory not empty, rename 'lingua-franca' -> '../temp-lingua-franca89539275'] {
  errno: -39,
  code: 'ENOTEMPTY',
  syscall: 'rename',
  path: 'lingua-franca',
  dest: '../temp-lingua-franca89539275'
}
npm notice 
npm notice New minor version of npm available! 9.6.6 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 
npm ERR! code 1
npm ERR! path /home/chadlia/berkeleyWorkspace/vscode-lingua-franca
npm ERR! command failed
npm ERR! command sh -c npm run clean && npm run build && npm run package && npm run deploy

npm ERR! A complete log of this run can be found in: /home/chadlia/.npm/_logs/2023-08-14T19_38_49_082Z-debug-0.log
````

which means that `npm run package` did not succeed, and therefore `npm run deploy` as well... right?
Please note that I couldn't update to the minor new version of `npm`... Could that be part of the issue? Maybe my `npm` is broken...?


> Regarding the java.lang.IllegalArgumentException: The code in its current state could not possibly produce the stack trace that you showed because createStateVariableLabel no longer calls FormattingUtil.render; instead, it directly invokes ToLf.instance.doSwitch. Therefore, your VS code extension is certainly not using the latest version of lingua-franca.

Indeed, @peter, `./gradlew build` after pulling solved the issue.
However:
> By the way, I think that the 0.4.2 release of the lingua-franca VS Code is WAY out of date, as illustrated by the syntax error that Soren mentioned. I would recommend that everyone switch to the pre-release version of the extension before reporting any new bugs:

I do actually have `Switch to Pre-Release Version`, as you can see here:

![Screenshot from 2023-08-14 13-28-53](https://github.com/lf-lang/lingua-franca/assets/37504116/45b5cb77-2cb4-4366-b878-5eb991ae7130)

And this does not solve the issue either. Actually, how can one know that it is the version on the machine that is used? I want to have it this way, so the editor does not complain about the WIP features I have...

**Comment by petervdonovan** [comment]
> My editor does not complain about the equal sign (in the textual version like yours).

I guess that must be because you clicked `npm install` at some point.

> I do actually have Switch to Pre-Release Version, as you can see here

If you have a button that says "Switch to Pre-Release Version" that means that you are **not** using the pre-release version, and you need to **click the button in order to switch to the pre-release version**.

>  Still, I just tried to run again npm install, and got this error

However if you do run `npm install`, then that should also give you an up-to-date version. This version will use whatever `lingua-franca` version is present in your `vscode-lingua-franca` directory as a submodule, so you can change the `lingua-franca` submodule as needed so that it does not have the breaking changes in your branch.

If you want to use `npm install` instead of clicking the "Switch to Pre-Release Version" button, e.g. because you want to have more control over the exact `lingua-franca` submodule version that you package, then it looks like you need to first **delete a directory named `../temp-lingua-franca89539275`** -- that is, `rm -rf ../temp-lingua-franca89539275`. We do some hacky shuffling of the directory structure in order to speed up the packaging process, and that `../temp-lingua-franca89539275` can be left behind if something goes wrong.

**Comment by ChadliaJerad** [comment]
> > My editor does not complain about the equal sign (in the textual version like yours).
> 
> I guess that must be because you ran `npm install` at some point.

I do, indeed!

> > I do actually have Switch to Pre-Release Version, as you can see here
> 
> If you have a button that says "Switch to Pre-Release Version" that means that you are **not** using the pre-release version, and you need to **click the button in order to switch to the pre-release version**.
> 

Yeah, but I am not using the releases on purpose, but rather have the latest updates from master, which are also, at some point pre-releases... 

> > Still, I just tried to run again npm install, and got this error
> 
> However if you do run `npm install`, then that should also give you an up-to-date version. This version will use whatever `lingua-franca` version is present in your `vscode-lingua-franca` directory as a submodule, so you can change the `lingua-franca` submodule as needed so that it does not have the breaking changes in your branch.
> 
> If you want to use `npm install` instead of clicking the "Switch to Pre-Release Version" button, e.g. because you want to have more control over the exact `lingua-franca` submodule version that you package, then it looks like you need to first **delete a directory named `../temp-lingua-franca89539275`** -- that is, `rm -rf ../temp-lingua-franca89539275`. We do some hacky shuffling of the directory structure in order to speed up the packaging process (see [lf-lang/vscode-lingua-franca#125](https://github.com/lf-lang/vscode-lingua-franca/pull/125)), and that `../temp-lingua-franca89539275` can be left behind if something goes wrong.

Done, and finally, it worked from outside the path! Many thanks, @petervdonovan!
I conclude that I was using an old local version. At some point, the build was broken, and maybe the project opened in the path was using binaries in the path (releases), while the one outside of the path was using the broken local ones...?!

Anyway, this is a solved issue now!
