### ISSUE TITLE
Open Diagram Fails once closed in Eclipse Theia

### ISSUE THREAD

**Issue by mkhubaibumer** [lf-lang/lingua-franca#2028]
As per our discussion in the last call we have forked the main `Theia-Blueprint` repository which can be obtained from [here](https://github.com/MagnitionIO/theia-blueprint.git)

Branch: `lingua-franca`

# Build Requirements:
`Node v14.21.3`

# Build Steps:
```
yarn && yarn build && yarn download:plugins
```
# To Run Browser app:
```
yarn browser start
```

This should have the KLighD and Lingua-Franca Extension as builtin

The problem we are facing is that once a lingua-franca diagram is closed we are unable to reopen it until we remove the persistence directory `~/.theia` and restart the application

# Steps to Reproduce the issue:

 - Run Theia (browser app/electron app)
 - Open any Lingua-Franca File
 - Diagram webview should open
 - Close the Diagram view
 - Try to reopen this from the Open Diagram button or from context menu

**Comment by NiklasRentzCAU** [comment]
I tried building the your theia-blueprint repository with the provided build step and node 14.21.3 and got this exception while building, therefore I currently cannot reproduce your issue to look at it.

```
> blueprint-browser-app:"build:prod"

blueprint-browser-app: $ yarn -s rebuild && theia  build --app-target="browser"
blueprint-browser-app: native node modules are already rebuilt for browser

> blueprint-electron-app:"build:prod"

blueprint-electron-app: $ yarn -s rebuild && theia build --app-target="electron"
blueprint-electron-app: Module not found: find-git-repositories
blueprint-electron-app: Module not found: ssh2
blueprint-electron-app: Module not found: cpu-features
blueprint-electron-app: Processed "node-pty"
blueprint-electron-app: Processed "keytar"
blueprint-electron-app: Processed "nsfw"
blueprint-electron-app: Processed "drivelist"
blueprint-electron-app: Processed "native-keymap"
blueprint-electron-app: - Searching dependency tree
blueprint-electron-app: make: Entering directory '/home/nre/git/theia-blueprint/node_modules/drivelist/build'
blueprint-electron-app:   CXX(target) Release/obj.target/drivelist/src/drivelist.o
blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
blueprint-electron-app:                  from ../../nan/nan.h:60,
blueprint-electron-app:                  from ../src/drivelist.cpp:17:
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
blueprint-electron-app:   256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
blueprint-electron-app:       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: In file included from ../src/drivelist.cpp:17:
blueprint-electron-app: ../../nan/nan.h:206:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
blueprint-electron-app:   206 |     public v8::CopyablePersistentTraits<T> {};
blueprint-electron-app:       |                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
blueprint-electron-app:                  from ../../nan/nan.h:60,
blueprint-electron-app:                  from ../src/drivelist.cpp:17:
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app:   CXX(target) Release/obj.target/drivelist/src/device-descriptor.o
blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
blueprint-electron-app:                  from ../../nan/nan.h:60,
blueprint-electron-app:                  from ../src/device-descriptor.cpp:17:
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
blueprint-electron-app:   256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
blueprint-electron-app:       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: In file included from ../src/device-descriptor.cpp:17:
blueprint-electron-app: ../../nan/nan.h:206:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
blueprint-electron-app:   206 |     public v8::CopyablePersistentTraits<T> {};
blueprint-electron-app:       |                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
blueprint-electron-app:                  from ../../nan/nan.h:60,
blueprint-electron-app:                  from ../src/device-descriptor.cpp:17:
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app:   CXX(target) Release/obj.target/drivelist/src/linux/list.o
blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
blueprint-electron-app:                  from ../../nan/nan.h:60,
blueprint-electron-app:                  from ../src/linux/list.cpp:17:
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
blueprint-electron-app:   256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
blueprint-electron-app:       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: In file included from ../src/linux/list.cpp:17:
blueprint-electron-app: ../../nan/nan.h:206:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
blueprint-electron-app:   206 |     public v8::CopyablePersistentTraits<T> {};
blueprint-electron-app:       |                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
blueprint-electron-app:                  from ../../nan/nan.h:60,
blueprint-electron-app:                  from ../src/linux/list.cpp:17:
blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
blueprint-electron-app:   SOLINK_MODULE(target) Release/obj.target/drivelist.node
blueprint-electron-app:   COPY Release/drivelist.node
blueprint-electron-app: make: Leaving directory '/home/nre/git/theia-blueprint/node_modules/drivelist/build'
blueprint-electron-app: Package libsecret-1 was not found in the pkg-config search path.
blueprint-electron-app: Perhaps you should add the directory containing `libsecret-1.pc'
blueprint-electron-app: to the PKG_CONFIG_PATH environment variable
blueprint-electron-app: No package 'libsecret-1' found
blueprint-electron-app: gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
blueprint-electron-app: ✖ Rebuild Failed
blueprint-electron-app: 
blueprint-electron-app: An unhandled error occurred inside electron-rebuild
blueprint-electron-app: node-gyp failed to rebuild '/home/nre/git/theia-blueprint/node_modules/keytar'.
blueprint-electron-app: For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
blueprint-electron-app: 
blueprint-electron-app: Error: `gyp` failed with exit code: 1
blueprint-electron-app: 
blueprint-electron-app: 
blueprint-electron-app: 
blueprint-electron-app: Error: node-gyp failed to rebuild '/home/nre/git/theia-blueprint/node_modules/keytar'.
blueprint-electron-app: For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
blueprint-electron-app: 
blueprint-electron-app: Error: `gyp` failed with exit code: 1
blueprint-electron-app: 
blueprint-electron-app: 
blueprint-electron-app:     at NodeGyp.rebuildModule (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:120:19)
blueprint-electron-app:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
blueprint-electron-app:     at async ModuleRebuilder.rebuildNodeGypModule (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/module-rebuilder.js:98:9)
blueprint-electron-app:     at async ModuleRebuilder.rebuild (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/module-rebuilder.js:128:14)
blueprint-electron-app:     at async Rebuilder.rebuildModuleAt (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/rebuild.js:149:13)
blueprint-electron-app:     at async Rebuilder.rebuild (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
blueprint-electron-app:     at async /home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/cli.js:158:9
blueprint-electron-app: Reverted "node-pty"
blueprint-electron-app: Reverted "keytar"
blueprint-electron-app: Reverted "nsfw"
blueprint-electron-app: Reverted "drivelist"
blueprint-electron-app: Reverted "native-keymap"
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Running target build:prod for 2 projects failed

   Failed tasks:
   
   - blueprint-electron-app:build:prod

```

**Comment by mkhubaibumer** [comment]
> I tried building the your theia-blueprint repository with the provided build step and node 14.21.3 and got this exception while building, therefore I currently cannot reproduce your issue to look at it.
> 
> ```
> > blueprint-browser-app:"build:prod"
> 
> blueprint-browser-app: $ yarn -s rebuild && theia  build --app-target="browser"
> blueprint-browser-app: native node modules are already rebuilt for browser
> 
> > blueprint-electron-app:"build:prod"
> 
> blueprint-electron-app: $ yarn -s rebuild && theia build --app-target="electron"
> blueprint-electron-app: Module not found: find-git-repositories
> blueprint-electron-app: Module not found: ssh2
> blueprint-electron-app: Module not found: cpu-features
> blueprint-electron-app: Processed "node-pty"
> blueprint-electron-app: Processed "keytar"
> blueprint-electron-app: Processed "nsfw"
> blueprint-electron-app: Processed "drivelist"
> blueprint-electron-app: Processed "native-keymap"
> blueprint-electron-app: - Searching dependency tree
> blueprint-electron-app: make: Entering directory '/home/nre/git/theia-blueprint/node_modules/drivelist/build'
> blueprint-electron-app:   CXX(target) Release/obj.target/drivelist/src/drivelist.o
> blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
> blueprint-electron-app:                  from ../../nan/nan.h:60,
> blueprint-electron-app:                  from ../src/drivelist.cpp:17:
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
> blueprint-electron-app:   256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
> blueprint-electron-app:       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
> blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
> blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: In file included from ../src/drivelist.cpp:17:
> blueprint-electron-app: ../../nan/nan.h:206:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
> blueprint-electron-app:   206 |     public v8::CopyablePersistentTraits<T> {};
> blueprint-electron-app:       |                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
> blueprint-electron-app:                  from ../../nan/nan.h:60,
> blueprint-electron-app:                  from ../src/drivelist.cpp:17:
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
> blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
> blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app:   CXX(target) Release/obj.target/drivelist/src/device-descriptor.o
> blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
> blueprint-electron-app:                  from ../../nan/nan.h:60,
> blueprint-electron-app:                  from ../src/device-descriptor.cpp:17:
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
> blueprint-electron-app:   256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
> blueprint-electron-app:       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
> blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
> blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: In file included from ../src/device-descriptor.cpp:17:
> blueprint-electron-app: ../../nan/nan.h:206:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
> blueprint-electron-app:   206 |     public v8::CopyablePersistentTraits<T> {};
> blueprint-electron-app:       |                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
> blueprint-electron-app:                  from ../../nan/nan.h:60,
> blueprint-electron-app:                  from ../src/device-descriptor.cpp:17:
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
> blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
> blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app:   CXX(target) Release/obj.target/drivelist/src/linux/list.o
> blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
> blueprint-electron-app:                  from ../../nan/nan.h:60,
> blueprint-electron-app:                  from ../src/linux/list.cpp:17:
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
> blueprint-electron-app:   256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
> blueprint-electron-app:       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
> blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
> blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: In file included from ../src/linux/list.cpp:17:
> blueprint-electron-app: ../../nan/nan.h:206:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
> blueprint-electron-app:   206 |     public v8::CopyablePersistentTraits<T> {};
> blueprint-electron-app:       |                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app: In file included from /home/nre/.electron-gyp/23.3.13/include/node/v8-object.h:10,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8-array-buffer.h:13,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/v8.h:24,
> blueprint-electron-app:                  from /home/nre/.electron-gyp/23.3.13/include/node/node.h:79,
> blueprint-electron-app:                  from ../../nan/nan.h:60,
> blueprint-electron-app:                  from ../src/linux/list.cpp:17:
> blueprint-electron-app: /home/nre/.electron-gyp/23.3.13/include/node/v8-persistent-handle.h:255:48: note: declared here
> blueprint-electron-app:   255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
> blueprint-electron-app:       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
> blueprint-electron-app:   SOLINK_MODULE(target) Release/obj.target/drivelist.node
> blueprint-electron-app:   COPY Release/drivelist.node
> blueprint-electron-app: make: Leaving directory '/home/nre/git/theia-blueprint/node_modules/drivelist/build'
> blueprint-electron-app: Package libsecret-1 was not found in the pkg-config search path.
> blueprint-electron-app: Perhaps you should add the directory containing `libsecret-1.pc'
> blueprint-electron-app: to the PKG_CONFIG_PATH environment variable
> blueprint-electron-app: No package 'libsecret-1' found
> blueprint-electron-app: gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> blueprint-electron-app: ✖ Rebuild Failed
> blueprint-electron-app: 
> blueprint-electron-app: An unhandled error occurred inside electron-rebuild
> blueprint-electron-app: node-gyp failed to rebuild '/home/nre/git/theia-blueprint/node_modules/keytar'.
> blueprint-electron-app: For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
> blueprint-electron-app: 
> blueprint-electron-app: Error: `gyp` failed with exit code: 1
> blueprint-electron-app: 
> blueprint-electron-app: 
> blueprint-electron-app: 
> blueprint-electron-app: Error: node-gyp failed to rebuild '/home/nre/git/theia-blueprint/node_modules/keytar'.
> blueprint-electron-app: For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
> blueprint-electron-app: 
> blueprint-electron-app: Error: `gyp` failed with exit code: 1
> blueprint-electron-app: 
> blueprint-electron-app: 
> blueprint-electron-app:     at NodeGyp.rebuildModule (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:120:19)
> blueprint-electron-app:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> blueprint-electron-app:     at async ModuleRebuilder.rebuildNodeGypModule (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/module-rebuilder.js:98:9)
> blueprint-electron-app:     at async ModuleRebuilder.rebuild (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/module-rebuilder.js:128:14)
> blueprint-electron-app:     at async Rebuilder.rebuildModuleAt (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/rebuild.js:149:13)
> blueprint-electron-app:     at async Rebuilder.rebuild (/home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/rebuild.js:112:17)
> blueprint-electron-app:     at async /home/nre/git/theia-blueprint/node_modules/electron-rebuild/lib/src/cli.js:158:9
> blueprint-electron-app: Reverted "node-pty"
> blueprint-electron-app: Reverted "keytar"
> blueprint-electron-app: Reverted "nsfw"
> blueprint-electron-app: Reverted "drivelist"
> blueprint-electron-app: Reverted "native-keymap"
> error Command failed with exit code 255.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
>  ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
> 
>  >  Lerna (powered by Nx)   Running target build:prod for 2 projects failed
> 
>    Failed tasks:
>    
>    - blueprint-electron-app:build:prod
> ```

@NiklasRentzCAU please install libsecret and try again. try with
`sudo apt-get install libsecret-1-dev`

**Comment by lhstrh** [comment]
@NiklasRentzCAU were you able to build (and reproduce the issue) after installing `libsecret-1-dev`?

**Comment by NiklasRentzCAU** [comment]
Yes, we were able to reproduce the issue with this. However, our problem with pinpointing the issue in this setup is that this just installs our extensions via their .vsix files, where we cannot debug any further than you already did - it just does not fully work in Theia. Our best guess is that some part of the Theia implementation does not fully conform to the way VS Code itself handles their extensions, thus causing the issue. As we do not have any setup to debug our software in Theia we will currently not further look into this issue. Our supported use case for the extension remains in VS Code, anything further is experimental.
