### ISSUE TITLE
Unable to generate diagrams in Windows using Visual Studio Code.

### ISSUE THREAD

**Issue by jackyk02** [lf-lang/lingua-franca#2072]
**Error Message:**
```An exception occurred during diagram synthesis\ java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: \\\c:\Users\jacky\Desktop\results\sample_efficiency\sample_efficiency\sample_efficiency.lf \ &nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212) \ &nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111) \ &nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) \ &nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) \ &nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) \ &nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.nio.file.Path.of(Path.java:147) \ &nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.CodeMap$Correspondence.tag(CodeMap.java:144) \ &nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.ASTUtils.toText(ASTUtils.java:693) \ &nbsp;&nbsp;&nbsp;&nbsp;```

![image](https://github.com/lf-lang/lingua-franca/assets/77720778/42de7e2f-dbc0-4395-a815-08123e11049c)

**Comment by lhstrh** [comment]
Thanks for the bug report, @jackyk02!
