### ISSUE TITLE
STP offsets cause lfc to fail

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#2155]
In the federated-cleanup branch (at least), the following example causes lfc-dev to fail:
```
target C {
  coordination: decentralized
}
reactor Sensor(period: time = 500ms) {
  output y:int
}
reactor Print {
  input x: int
  input z: int
  reaction(x) {=
  =} STP(20 ms) {=
  =}
  reaction(z) {=
  =} STP(20 ms) {=
  =}
}
federated reactor {
  s = new Sensor()
  p = new Print()
  
  s.y -> p.x
  s.y -> p.z
}
```
The failure is:
```
lfc: fatal error: Error running generator
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.HashMap.get(Object)" is null
        at org.lflang.federated.generator.FedASTUtils.addNetworkReceiverReactor(FedASTUtils.java:308)
        at org.lflang.federated.generator.FedASTUtils.makeCommunication(FedASTUtils.java:149)
        at org.lflang.federated.generator.FedGenerator.replaceFederateConnectionsWithProxies(FedGenerator.java:638)
        at org.lflang.federated.generator.FedGenerator.doGenerate(FedGenerator.java:157)
        at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:105)
        at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
...
```

**Comment by edwardalee** [comment]
This is fixed now in commit fbbf9deaf021708d4cf2b2363f1d5650ebb69b6b.  The problem was that TimeValue failed to override `hashCode()` even though it had implemented `equals()`. The bug was triggered when two STP offsets were identical.
