### ISSUE TITLE
Error in Diagram Synthesis

### ISSUE THREAD

**Issue by jjrev** [lf-lang/lingua-franca#2166]
Using VSCode on Windows 11 with JDK 17 installed, I see the following error message when I try to display the diagram for a given *.lf file (doesn't matter which):
```
An exception occurred during diagram synthesis\
java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: \\\c:\Users\xxxxxxxx\Development\lingua-franca\test\C\src\Deadline.lf
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
\
&nbsp;&nbsp;&nbsp;&nbsp;at java.base/java.nio.file.Path.of(Path.java:147)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.CodeMap$Correspondence.tag(CodeMap.java:144)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.ast.ASTUtils.toText(ASTUtils.java:693)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactionInstance.&lt;init&gt;(ReactionInstance.java:70)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.createReactionInstances(ReactorInstance.java:758)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.&lt;init&gt;(ReactorInstance.java:902)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.&lt;init&gt;(ReactorInstance.java:882)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.generator.ReactorInstance.&lt;init&gt;(ReactorInstance.java:105)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:322)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.synthesis.LinguaFrancaSynthesis.transform(LinguaFrancaSynthesis.java:144)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.syntheses.AbstractDiagramSynthesis.transform(AbstractDiagramSynthesis.java:220)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.syntheses.ReinitializingDiagramSynthesisProxy.transform(ReinitializingDiagramSynthesisProxy.java:289)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:454)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:389)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.ViewContext.update(ViewContext.java:346)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.lsp.KGraphDiagramUpdater.lambda$6(KGraphDiagramUpdater.java:267)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.lambda$1(AbstractLanguageServer.java:117)
\
&nbsp;&nbsp;&nbsp;&nbsp;at de.cau.cs.kieler.klighd.lsp.launch.AbstractLanguageServer.configureAndRun(AbstractLanguageServer.java:96)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.lsp.LanguageDiagramServer.start(LanguageDiagramServer.java:111)
\
&nbsp;&nbsp;&nbsp;&nbsp;at org.lflang.diagram.lsp.LanguageDiagramServer.main(LanguageDiagramServer.java:107)
```

Per a request from @a-sr, copying this issue here from original issue: https://github.com/kieler/klighd-vscode/issues/166#issue-2098586755

**Comment by lhstrh** [comment]
I suppose `\\\c:\Users\xxxxxxxx\Development\lingua-franca\test\C\src\Deadline.lf` isn't a valid path on Windows. What is the correct path?

**Comment by jjrev** [comment]
Correct.  Just pasting that path into Explorer doesn't work.  

Side note, I downloaded the Epoch IDE (on the same machine) and diagrams render correctly.

**Comment by jjrev** [comment]
Unsure if this is related but I'm also seeing the following error on any *.lf file at the first line (regardless of what that line is):
```
Error executing EValidator(org.eclipse.emf.ecore.impl.EClassImpl@238915d2 (name: Model) (instanceClassName: null) (abstract: false, interface: false).0)
```

**Comment by lhstrh** [comment]
Seems like a trivial bug, but this would require help from a developer who runs on Windows. I flagged it as such.

**Comment by jjrev** [comment]
Another interesting detail is that this issue does **not** manifest if I use WSL to launch VSCode.

**Comment by lhstrh** [comment]
> Another interesting detail is that this issue does **not** manifest if I use WSL to launch VSCode.

That makes sense though, because in a WSL environment straightforward Linux paths are used. What is the correct version of `\\\c:\Users\xxxxxxxx\Development\lingua-franca\test\C\src\Deadline.lf`?

**Comment by jjrev** [comment]
I gave up trying to get the ```/mnt/c/Users/...``` path to load in VSCode launched from WSL (due to permission issues) and just cloned the repo to my WSL home directory.
