### ISSUE TITLE
StringIndexOutOfBoundsException when reporting error

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#490]
Running LFC on the following file:
```py
target Python;
main reactor R(p(3)) {
  state liss(2, 3);
  reaction (startup) {
    print(self.liss)
}
}
```
produces the following exception (the error is normal):

```
lfc: error: missing '{=' at '{'
--> R.lf:5:20
  |
4 | 
5 | reaction (startup) {
  |                    ^ missing '{=' at '{'
  |
6 |   print(self.liss)

lfc: fatal error: An unexpected error occurred:
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.String.substring(String.java:2691)
	at org.lflang.generator.ReportingBackend$MessageTextBuilder$makeErrorLine$1.invoke(ReportingUtil.kt:299)
	at org.lflang.generator.ReportingBackend$MessageTextBuilder.makeErrorLine(ReportingUtil.kt:303)
	at org.lflang.generator.ReportingBackend$MessageTextBuilder.build(ReportingUtil.kt:271)
	at org.lflang.generator.ReportingBackend.formatIssue(ReportingUtil.kt:239)
	at org.lflang.generator.ReportingBackend.printIssue(ReportingUtil.kt:213)
	at org.lflang.generator.Main$$Lambda$109/0x0000000000000000.accept(Unknown Source)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4421)
	at org.lflang.generator.Main.exitIfCollectedErrors(Main.java:493)
	at org.lflang.generator.Main.runGenerator(Main.java:468)
	at org.lflang.generator.Main.main(Main.java:266)
```

**Comment by cmnrd** [comment]
This seems to be another example for #461
