### ISSUE TITLE
CGenerator incorrectly detects cycles with physical connections as causality loops

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#578]
I've pushed a fix for `TopologyGraph` (see https://github.com/lf-lang/lingua-franca/pull/577) that addresses the faulty behavior in the validator and diagrams reported in this issue. I think it deals accordingly with physical connections as well as connections that have an `after`. It exposed another bug, however, namely that the cycle detection performed in the code generator still reports a cycle even if it is broken by a physical connection:

```
java.lang.Exception: Reactions form a cycle!
	at org.lflang.generator.ReactionInstanceGraph.rebuild(ReactionInstanceGraph.java:59)
	at org.lflang.generator.ReactionInstanceGraph.<init>(ReactionInstanceGraph.java:44)
	at org.lflang.generator.c.CGenerator.doGenerate(CGenerator.java:716)
	at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:165)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:597)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:578)
	at org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:563)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:303)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:265)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:164)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:70)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:392)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:322)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:303)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:208)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:160)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:251)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

@edwardalee  could you have a look?

_Originally posted by @lhstrh in https://github.com/lf-lang/lingua-franca/issues/447#issuecomment-937109589_

**Comment by lhstrh** [comment]
There are other operations happening in the generator that have cycle detection as a side effect. It's one of those "this should not happen" lines of code that gets triggered.
