### ISSUE TITLE
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#859]
I get the following exception on `master` on commit b7d6115d636e315710c2717220f215a7e8362ff3 when compiling any of the Python tests:

```bash
$ lfc test/Python/srcMinimal.lf 
Generating code for: file:/home/soroush/lingua-franca-master/git/lingua-franca/test/Python/src/Minimal.lf
******** Mode: STANDALONE
******** Generated sources: /home/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/Minimal
******** Using 1 threads.
Generating setup file to /home/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/Minimal/setup.py
--- Current working directory: /home/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/Minimal
--- Executing command: pylint --output-format=json Minimal.py
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at org.lflang.generator.python.PythonValidator$2.lambda$getOutputReportingStrategy$2(PythonValidator.java:249)
	at org.lflang.generator.Validator.doValidate(Validator.java:64)
	at org.lflang.generator.python.PythonGenerator.doGenerate(PythonGenerator.java:1809)
	at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:163)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.lflang.lfc.Main.runGenerator(Main.java:277)
	at org.lflang.lfc.Main.main(Main.java:206)
--- Current working directory: /home/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/Minimal
--- Executing command: python3 -m pip install --force-reinstall .
Processing /home/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/Minimal
WARNING: Ignoring invalid distribution -inguafrancacarlaintersection-vehicles-0 (/home/soroush/.pyenv/versions/3.7.10/lib/python3.7/site-packages)
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Collecting LinguaFrancaBase
  Using cached LinguaFrancaBase-1.0.3-py3-none-any.whl (3.4 kB)
Using legacy 'setup.py install' for LinguaFrancaMinimal, since package 'wheel' is not installed.
Installing collected packages: LinguaFrancaBase, LinguaFrancaMinimal
  Attempting uninstall: LinguaFrancaBase
    Found existing installation: LinguaFrancaBase 1.0.3
    Uninstalling LinguaFrancaBase-1.0.3:
      Successfully uninstalled LinguaFrancaBase-1.0.3
  Attempting uninstall: LinguaFrancaMinimal
    Found existing installation: LinguaFrancaMinimal 1.0
    Can't uninstall 'LinguaFrancaMinimal'. No files were found to uninstall.
    Running setup.py install for LinguaFrancaMinimal: started
WARNING: Ignoring invalid distribution -inguafrancacarlaintersection-vehicles-0 (/home/soroush/.pyenv/versions/3.7.10/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -inguafrancacarlaintersection-vehicles-0 (/home/soroush/.pyenv/versions/3.7.10/lib/python3.7/site-packages)
    Running setup.py install for LinguaFrancaMinimal: finished with status 'done'
Successfully installed LinguaFrancaBase-1.0.3 LinguaFrancaMinimal-1.0
WARNING: Ignoring invalid distribution -inguafrancacarlaintersection-vehicles-0 (/home/soroush/.pyenv/versions/3.7.10/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inguafrancacarlaintersection-vehicles-0 (/home/soroush/.pyenv/versions/3.7.10/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inguafrancacarlaintersection-vehicles-0 (/home/soroush/.pyenv/versions/3.7.10/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inguafrancacarlaintersection-vehicles-0 (/home/soroush/.pyenv/versions/3.7.10/lib/python3.7/site-packages)
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/home/soroush/.pyenv/versions/3.7.10/bin/python3 -m pip install --upgrade pip' command.
Successfully installed python extension.

#####################################
To run the generated program, use:
    
    python3 /home/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/Minimal/Minimal.py

#####################################

Code generation finished.
```

`lfc` also seemingly freezes for federated programs, such as ` test/Python/src/federated/BroadcastFeedback.lf`.
I can confirm that I don't see this behavior in the `c-new-scheduler` branch.

**Comment by petervdonovan** [comment]
This is apparently because of the `vscode-validate-generated-code` branch that I just merged. It is very surprising to me that this happened, because that branch passed test cases from every test category for every target and seemed to work okay on my machine. I will look into this either tonight or tomorrow.

**Comment by Soroosh129** [comment]
Thanks for fixing this issue. In the end, the exception persisted but the warning `The Lingua Franca code generator is tested with Pylint version 2.12.2` was very helpful. Installing Pylint (`pip3 install pylint`) resolved the issue.
