### ISSUE TITLE
multiple unnamed main reactor causes nullPointerException

### ISSUE THREAD

**Issue by housengw** [lf-lang/lingua-franca#905]
minimal example 
```
target C;
main reactor {}
main reactor {}
```

output
```
Generating code for: file: ...
******** mode: STANDALONE
******** source file: ...
******** generated sources: ...
******** generated binaries: ...
******** Using 1 threads.
lfc: fatal error: An unexpected error occurred:
java.lang.NullPointerException
	at org.lflang.generator.c.CGenerator.selfStructType(CGenerator.java:5419)
	at org.lflang.generator.c.CGenerator.generateSelfStruct(CGenerator.java:2554)
	at org.lflang.generator.c.CGenerator.generateReactorFederated(CGenerator.java:2185)
	at org.lflang.generator.c.CGenerator.generateReactorDefinitionsForFederate(CGenerator.java:1333)
	at org.lflang.generator.c.CGenerator.doGenerate(CGenerator.java:774)
	at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:163)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.lflang.lfc.Main.runGenerator(Main.java:278)
	at org.lflang.lfc.Main.main(Main.java:207)
```

Having multiple unnamed federated reactor does not cause this issue.

**Comment by housengw** [comment]
the problem seems to be local to my laptop

**Comment by lhstrh** [comment]
The duplicate reactor check doesn't work on anonymous main reactors. The above example should trigger an error, which it currently doesn't.
