### ISSUE TITLE
invalid time literal causees IllegalArgumentException

### ISSUE THREAD

**Issue by housengw** [lf-lang/lingua-franca#908]
minimal example:
```
target C;
main reactor {
    timer t(0 m)
}
```

output
```
wonghouseng@beefy-desktop-linux:~/Desktop/lingua-franca/test/C$ lfc src/exp.lf 
0    [main] ERROR text.validation.CompositeEValidator  - Error executing EValidator
java.lang.IllegalArgumentException
	at org.lflang.JavaAstUtils.toTimeValue(JavaAstUtils.java:160)
	at org.lflang.JavaAstUtils.getLiteralTimeValue(JavaAstUtils.java:213)
	at org.lflang.generator.ReactorInstance.getTimeValue(ReactorInstance.java:635)
	at org.lflang.generator.TimerInstance.<init>(TimerInstance.java:65)
	at org.lflang.generator.ReactorInstance.<init>(ReactorInstance.java:816)
```

**Comment by housengw** [comment]
fixec by #916
