### ISSUE TITLE
Epoch fails with IllegalStateException when compiling C++ programs via the code generation button

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#929]
Stack trace:
```
java.lang.IllegalStateException: This must only be called once on a given progress monitor instance.
	at org.eclipse.core.runtime.SlicedProgressMonitor.beginTask(SlicedProgressMonitor.java:41)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:483)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:449)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.syncIfNecessary(EclipseResourceFileSystemAccess2.java:545)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.syncIfNecessary(EclipseResourceFileSystemAccess2.java:538)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.getTraceFile(EclipseResourceFileSystemAccess2.java:531)
	at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.generateFile(EclipseResourceFileSystemAccess2.java:212)
	at org.eclipse.xtext.generator.AbstractFileSystemAccess.generateFile(AbstractFileSystemAccess.java:100)
	at org.lflang.generator.cpp.CppGenerator.generateFiles(CppGenerator.kt:119)
	at org.lflang.generator.cpp.CppGenerator.doGenerate(CppGenerator.kt:70)
	at org.lflang.generator.LFGenerator.doGenerate(LFGenerator.java:163)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.lflang.ui.actions.CompileActionHandler$1.run(CompileActionHandler.java:216)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This seems to be related to the usage of the `AbstractFileSystemAccess` interface of the C++ generator, but I am not sure why this error is triggered.

**Comment by lhstrh** [comment]
@petervdonovan is working on a fix; I will merge that in, re-tag `v0.1.0-beta`, and upload new build artifacts.
